/* CONTROL FLOW - IF | ELSE IF | ELSE | SWITCH 

CONTROL FLOW IN JAVASCRIPT APPLIES TO CONDITIONAL STATEMENTS. THESE CONDITIONS AND THE FLOW OF COMMANDS ARE WRITTEN
WITH IF/ELSE IF/ELSE/SWITCH

0. IF 

THE IF STATEMENT IS USUALLY THE FIRST CONDITIONAL STATEMENT IN A FUNCTION. IF THE INSTANCE RESOLVES TO TRUE THE CODE 
BLOCK UNDERNEATH THE IF STATEMENT WILL RUN FOR INSTANCE:

function myFunction(fahrenheit){
    if(fahrenheit < 60) {
        console.log('im chilly');
    } else if (fahrenheit < 20){
        console.log('im freezing');
    }
}

myFunction(53);

NOW WHEN I CALL THE FUNCTION AND THE FARHRENHEIT IS LESS THAN 60 THE CONSOLE WILL LOG 'IM CHILLY' AND THE CONDITIONAL
STATEMNENTS UNDERNEATH IT WILL NOT BE TESTED. 

1. THE ELSE IF STATEMENT WILL TYPICALLY FOLLOW THE FIRST CONDITIONAL STATEMENT OF IF. ELSE IF MEANS IF THE THE 
CONDITIONAL STATEMENTS BEFORE THE ELSE IF STATEMENT DO NOT RESOLVE TO TRUE - THIS STATEMENT WILL IN TURN BE TESTED. 
IF THIS ELSE IF STATEMENT RESOLVES TO TRUE THEN THE CODE BLOCK UNDERNEATH IT WILL RUN. THERE CAN BE MULTIPLE IF
ELSE STATEMENTS IN A ROW. FOR EXAMPLE:

function myPet(animal){
    if(animal = 'dog'){
        console.log('basil');
    } else if(animal = 'cat'){
        console.log('oyster');
    } else if(animal = 'fish'){
        console.log('pisces');
    }
}

myPet('cat'); 

IN THIS CASE WHEN I CALL THE FUNCTION WITH 'cat' ONCE THAT RESOLVES TO TRUE THE CONDITIONS UNDERNEATH IT WILL NOT BE 
TESTED.

2.THE ELSE STATEMENT ACTS AS A CATCH ALL AND IS LISTED AT THE BOTTOM OF THE CONDITIONAL STATEMENT. IF NONE OF THE 
OTHER CASES RESOLVE TO TRUE, THE CODE BLOCK UNDERNEATH ELSE WILL RUN. FOR INSTANCE:

function myPet(animal){
    if(animal = 'dog'){
        console.log('basil');
    } else if(animal = 'cat'){
        console.log('oyster');
    } else (animal = 'unknown'){
        console.log('that's not my pet');
    }
}

myPet('rabbit'); 

IN THIS CASE WHEN I CALL THE FUNCTION AND NONE OF THE CONDITIONS MATCH THE VALUE, THE ELSE STATEMENT WILL RUN.

3. THE SWITCH STATEMENT 
