/* CONTROL FLOW - IF | ELSE IF | ELSE | SWITCH 

CONTROL FLOW IN JAVASCRIPT APPLIES TO CONDITIONAL STATEMENTS. THESE CONDITIONS 
AND THE FLOW OF COMMANDS ARE WRITTEN
WITH IF/ELSE IF/ELSE AND SWITCH STATEMENTS. 
IF ELSE STATEMENTS RELY ON THE TRUTHINESS OR FALSINESS IN ORDER TO RUN THEIR 
CODE BLOCK, WHILE SWITCH STATEMENTS ARE MORE SPECIFIC.


*/

/*1. IF 

THE IF STATEMENT IS USUALLY THE FIRST CONDITIONAL STATEMENT IN A FUNCTION.
IF THE INSTANCE RESOLVES TO TRUE THE CODE 
BLOCK UNDERNEATH THE IF STATEMENT WILL RUN FOR INSTANCE:
*/

function myFunction(fahrenheit){
    if(fahrenheit < 60) {
        console.log('im chilly');
    } else if (fahrenheit < 20){
        console.log('im freezing');
    }
}

myFunction(53); // prints to console => 'im chilly'

/*NOW WHEN I CALL THE FUNCTION AND THE FARHRENHEIT IS LESS THAN 60 THE CONSOLE 
WILL LOG 'IM CHILLY' AND THE CONDITIONAL
STATEMNENTS UNDERNEATH IT WILL NOT BE TESTED. 

2. THE ELSE IF STATEMENT WILL TYPICALLY FOLLOW THE FIRST CONDITIONAL STATEMENT 
OF IF. ELSE IF MEANS IF THE THE 
CONDITIONAL STATEMENTS BEFORE THE ELSE IF STATEMENT DO NOT RESOLVE TO TRUE - 
THIS STATEMENT WILL IN TURN BE TESTED. 
IF THIS ELSE IF STATEMENT RESOLVES TO TRUE THEN THE CODE BLOCK UNDERNEATH IT
WILL RUN. THERE CAN BE MULTIPLE IF
ELSE STATEMENTS IN A ROW. FOR EXAMPLE:
*/

 function myPet(animal){
    if(animal === 'dog'){
        console.log('basil');
    } else if(animal === 'cat'){
        console.log('oyster');
    } else if(animal === 'fish'){
        console.log('pisces');
    }
}

myPet('cat'); // => prints to console 'oyster'




//IN THIS CASE WHEN I CALL THE FUNCTION WITH 'cat' ONCE THAT RESOLVES TO TRUE 
//THE CONDITIONS UNDERNEATH IT WILL NOT BE 
//TESTED.

/*3.THE ELSE STATEMENT ACTS AS A CATCH ALL AND IS LISTED AT THE BOTTOM OF THE
CONTROL FLOW. IF NONE OF THE 
OTHER CASES RESOLVE TO TRUE, THE CODE BLOCK UNDERNEATH ELSE WILL RUN - REGARDLESS
OF TRUE OR FALSE VALUES. FOR INSTANCE:
*/

function myPet(animal){
    if(animal === 'dog'){
        console.log('basil');
    } else if(animal === 'cat'){
        console.log('oyster');
    } else 
        console.log('thats not my pet');
    }


myPet('rabbit'); // prints to console 'thats not my pet'


//IN THIS CASE WHEN I CALL THE FUNCTION AND NONE OF THE CONDITIONS MATCH THE 
//VALUE, THE ELSE STATEMENT WILL RUN.

/*4. THE SWITCH STATEMENT 

A SWITCH STATEMENT IS VERY SIMILAR TO ALL THE FOREMENTIONED STATEMENTS. ALTHOUGH 
ITS FORMATTING MIGHT SEEM DAUNTING
AT FIRST, USING THE SWITCH STATEMENT CAN BE EFFECTIVE FOR SPECIFIC CASE. 

REASONS YOU MIGHT WANT TO USE SWITCH:
- YOU NEED TO USE ALOT OF 'if' STATEMENTS 
- SPEED 
- LOOKS NICER!!
*/


var weather = 'Cold';
switch (weather) {
  case 'Hot':
    console.log('i need sunscreen');
    break;
  case 'drizzle':
  case 'storming':
    console.log('i need an umbrella');
    break;
  default:
    console.log('what a nice day out!');
}