/* DATATYPES
* 0. Number
* THE DATATYPE NUMBER SIGNIFIES THAT THE VALUE IS A MATHMATICAL NUMBER. THIS DATATYPE DOES NOT NEED TO BE LOGGED WITH 
*  SINGLE OR DOUBLE QUOTATION MARKS. FOR INSTANCE:
*/
  var myNum = 1;

/*  1. String
* THE DATATYPE STRING SIGNIFIES THAT THE VALUE IS A STRING OF CHARACTERS. THIS DATATYPE MUST BE IN SINGLE OR DOUBLE 
* QOUTATION MARKS. FOR INSTANCE:
*/
*
* var myString = 'string';
*
/* 2. Boolean
* THE DATATYPE BOOLEAN SIGNIFIES THAT THE VALUE WILL EITHER BE TRUE OR FALSE. THIS DATATYPE DOES NOT NEED TO IN 
* SINGLE OR DOUBLE QUOTATIONS. FOR INSTANCE:
*/
*
*  var myBool = true;
*
/* 3. Array
* THE DATATYPE ARRAY SIGNIFIES THAT THE VALUE WILL BE AN COLLECTION. THIS COLLECTION CAN BE A MIX OF DATAYPES. 
* IT MUST BE LISTED WITH BRACKETS. FOR INSTANCE:
*/
* 
* var myArray = ['dog', true, 1];
*
